services:
  app:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=CatApiAppDb;User=sa;Password=m3r3d@230592!;Trusted_Connection=False;TrustServerCertificate=True;
      - ConnectionStrings__Redis=redis:6379
    ports:
      - "8081:80"  # Use a different port for development if needed
    depends_on:
      - db
      - redis

  db:
    environment:
      SA_PASSWORD: "m3r3d@230592!"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserverdata_dev:/var/opt/mssql  # Use a different volume for development data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
      
volumes:
  sqlserverdata_dev:
